services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: v2-discord-bot

    restart: unless-stopped

    env_file:
      - .env

    volumes:
      - ./data:/app/data